version: "3.9"
services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
  
  account-service:
    build: ./account-service
    ports:
      - "5001:5001"
    depends_on:
      - auth-service
  
  transaction-service:
    build: ./transaction-service
    ports:
      - "5002:5002"
    depends_on:
      - account-service
